### ISSUE TITLE
Error undefined getData when another user joins a channel. I was not in any channel.

### ISSUE THREAD

**Issue by KuryGabriele** [KuryGabriele/echo-project#5]
![immagine](https://github.com/KuryGabriele/echo-project/assets/35193509/f6b10fc5-46d6-4e09-8190-b3d5f56d72c4)

**Comment by KuryGabriele** [comment]
Echo protocol line 376

**Comment by zThundy** [comment]
Fixed with commit 700d3e57903e5bc362262e67c988e12d75b225ad
