### ISSUE TITLE
Audio Sources not loading.

### ISSUE THREAD

**Issue by zThundy** [KuryGabriele/echo-project#6]
![image](https://github.com/KuryGabriele/echo-project/assets/25564154/172716ec-bb6c-4067-bd55-ffc0a2ae3800)

Add error handling for this issue.

**Comment by KuryGabriele** [comment]
This happens when the device is busy or unavailable. I added a print in console and this should not throw the error like this anymore, but we need to comunicate the error to the user because the stream will not start.
