### ISSUE TITLE
Different behaviour with Prod and Dev

### ISSUE THREAD

**Issue by zThundy** [KuryGabriele/echo-project#7]
Somehow the mute / unmute behaviour seems to be working in the dev environment, but not in the Prod environment.

![image](https://github.com/KuryGabriele/echo-project/assets/25564154/cc4896c1-1abb-4874-87ff-359db4165515)

**Comment by KuryGabriele** [comment]
The issue was part of joining a room while muted. Fixed in commit #15c9d1f
